apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_DB
          value: "taskflowdb-#{environmentName}"
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - taskflow
              - -d
              - taskflowdb-#{environmentName}
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - taskflow
              - -d
              - taskflowdb-#{environmentName}